---
driver:
  name: vagrant
provisioner:
  name: chef_zero
platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[ubuntu::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[ubuntu::default]
  - name: ubuntu-10.04
    run_list:
      - recipe[ubuntu::default]
  - name: centos-7.2
    run_list:
      - recipe[redhat::default]
  - name: centos-6.7
    run_list:
      - recipe[redhat::default]
  - name: centos-5.11
    run_list:
      - recipe[redhat::default]
suites:
  - name: default
    run_list:
      - recipe[collectd::default]
